### PR TITLE
Added VC Song Bot Guide 😉

### PR DESCRIPTION
**Pull request by xDistinct**

### CODE REVIEW

**Comment by buddhhu** [comment]
It will still work if no VC Session is found. But same acc will play

**Comment by xDistinct** [comment]
> It will still work if no VC Session is found. But same acc will play
I did this to add a new page for VC as I thought it will help users... I will explain all cmds if possible 👍

**Comment by New-dev0** [comment]
@xDistinct No, don't explain command in docs, leave it in help menu(s)

**Comment by xDistinct** [comment]
@New-dev0 then tell me what to add in this page?

**Pull request merged**
